title: cd80 Security Research
description: "Getting Revenge on Computers"
author:
  name: "cd80"
  email: ""
  url: "https://cd80-ctf.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "cd80"
year : "2023"
